// Smart POS — sample data (mixed restaurant + retail)
export const DATA = {
  merchant: {
    name: 'Northwind Hospitality',
    plan: 'Enterprise',
    locations: 14,
    terminals: 47,
  },
  kpis: [
    { label: 'Gross Sales', value: 184293, currency: '$', delta: '+12.4%', dir: 'up', spark: [12, 18, 14, 22, 19, 25, 28, 24, 30, 33, 29, 38] },
    { label: 'Orders', value: 2847, delta: '+8.1%', dir: 'up', spark: [10, 14, 12, 18, 16, 20, 22, 21, 24, 26, 23, 28] },
    { label: 'Avg. Ticket', value: 64.74, currency: '$', delta: '+3.9%', dir: 'up', spark: [20, 21, 22, 21, 23, 24, 23, 25, 26, 25, 27, 28] },
    { label: 'Refunds', value: 1247, currency: '$', delta: '-22%', dir: 'up', spark: [30, 28, 26, 24, 25, 22, 20, 21, 18, 16, 15, 12] },
  ],
  channels: [
    { name: 'Dine-in', value: 38, color: 'oklch(0.62 0.17 145)' },
    { name: 'Takeaway', value: 24, color: 'oklch(0.65 0.14 200)' },
    { name: 'Delivery', value: 22, color: 'oklch(0.70 0.15 70)' },
    { name: 'QR Order', value: 11, color: 'oklch(0.55 0.18 290)' },
    { name: 'Drive-thru', value: 5, color: 'oklch(0.60 0.18 25)' },
  ],
  merchants: [
    { id: 'M-001', name: 'Northwind Hospitality', email: 'maya@northwind.co', password: 'password123' },
    { id: 'M-002', name: 'Arbaz Tech', email: 'arbaz@tech.co', password: 'password123' },
  ],
  locations: [
    { id: 'L-001', merchantId: 'M-001', name: 'Flagship — SoHo', code: 'NYC-01', city: 'New York, NY', status: 'open', terminals: 8, staff: 24, sales: 28430, channels: ['Dine-in', 'Takeaway', 'Delivery'], type: 'Restaurant', email: 'soho@northwind.co', phone: '+1 212-555-0101', website: 'https://northwind.co/soho', logo: '', address: '123 Spring St, New York, NY 10012', country: 'United States' },
    { id: 'L-002', merchantId: 'M-001', name: 'Brooklyn Heights', code: 'NYC-02', city: 'Brooklyn, NY', status: 'open', terminals: 4, staff: 12, sales: 14820, channels: ['Dine-in', 'QR'], type: 'Cafe', email: 'brooklyn@northwind.co', phone: '+1 718-555-0122', website: 'https://northwind.co/brooklyn', logo: '', address: '88 Atlantic Ave, Brooklyn, NY 11201', country: 'United States' },
    { id: 'L-003', merchantId: 'M-001', name: 'Williamsburg Pop-up', code: 'NYC-03', city: 'Brooklyn, NY', status: 'closed', terminals: 2, staff: 6, sales: 4210, channels: ['Takeaway'], type: 'Cafe', email: 'williamsburg@northwind.co', phone: '+1 718-555-0133', website: 'https://northwind.co/williamsburg', logo: '', address: '45 Kent Ave, Brooklyn, NY 11249', country: 'United States' },
    { id: 'L-004', merchantId: 'M-001', name: 'Boston Seaport', code: 'BOS-01', city: 'Boston, MA', status: 'open', terminals: 6, staff: 18, sales: 19230, channels: ['Dine-in', 'Delivery'], type: 'Restaurant', email: 'seaport@northwind.co', phone: '+1 617-555-0144', website: 'https://northwind.co/seaport', logo: '', address: '200 Pier 4 Blvd, Boston, MA 02210', country: 'United States' },
    { id: 'L-005', merchantId: 'M-002', name: 'Chicago — West Loop', code: 'CHI-01', city: 'Chicago, IL', status: 'open', terminals: 5, staff: 16, sales: 22140, channels: ['Dine-in', 'Delivery', 'Drive-thru'], type: 'QSR', email: 'westloop@northwind.co', phone: '+1 312-555-0155', website: 'https://northwind.co/westloop', logo: '', address: '450 W Fulton Market, Chicago, IL 60661', country: 'United States' },
    { id: 'L-006', merchantId: 'M-002', name: 'Lincoln Park Retail', code: 'CHI-02', city: 'Chicago, IL', status: 'open', terminals: 3, staff: 7, sales: 8910, channels: ['In-store'], type: 'Retail', email: 'lincolnpark@northwind.co', phone: '+1 312-555-0166', website: 'https://northwind.co/lincolnpark', logo: '', address: '1347 N Halsted St, Chicago, IL 60642', country: 'United States' },
  ],

  products: [
    { id: 'P-1024', sku: 'BRG-CLS-001', name: 'Northwind Classic Burger', category: 'Burgers', price: 14.50, cost: 4.20, stock: 142, status: 'active', channels: ['Dine-in', 'Delivery', 'QR'], modifiers: 4, type: 'Restaurant' },
    { id: 'P-1025', sku: 'BRG-VEG-002', name: 'Smashed Mushroom Burger', category: 'Burgers', price: 13.00, cost: 3.80, stock: 88, status: 'active', channels: ['Dine-in', 'Delivery'], modifiers: 4, type: 'Restaurant' },
    { id: 'P-1026', sku: 'BRG-DBL-003', name: 'Double Stack Cheeseburger', category: 'Burgers', price: 17.50, cost: 5.40, stock: 64, status: 'active', channels: ['Dine-in', 'Delivery', 'QR'], modifiers: 5, type: 'Restaurant' },
    { id: 'P-2031', sku: 'CFE-LAT-001', name: 'Oat Milk Latte', category: 'Coffee', price: 5.75, cost: 1.20, stock: 999, status: 'active', channels: ['Dine-in', 'Takeaway', 'QR'], modifiers: 6, type: 'Cafe' },
    { id: 'P-2032', sku: 'CFE-AME-002', name: 'Single-origin Americano', category: 'Coffee', price: 4.50, cost: 0.85, stock: 999, status: 'active', channels: ['Dine-in', 'Takeaway'], modifiers: 3, type: 'Cafe' },
    { id: 'P-2033', sku: 'CFE-CAP-003', name: 'Cortado', category: 'Coffee', price: 4.25, cost: 0.90, stock: 999, status: 'active', channels: ['Dine-in', 'Takeaway'], modifiers: 3, type: 'Cafe' },
    { id: 'P-3014', sku: 'PZA-MAR-001', name: 'Margherita Pizza', category: 'Pizza', price: 18.00, cost: 5.10, stock: 32, status: 'active', channels: ['Dine-in', 'Delivery'], modifiers: 3, type: 'Restaurant' },
    { id: 'P-3015', sku: 'PZA-PEP-002', name: 'Pepperoni Pizza', category: 'Pizza', price: 19.50, cost: 5.60, stock: 28, status: 'low', channels: ['Dine-in', 'Delivery'], modifiers: 3, type: 'Restaurant' },
    { id: 'P-4001', sku: 'APP-TEE-BLK', name: 'Heritage Tee — Black', category: 'Apparel', price: 38.00, cost: 12.40, stock: 124, status: 'active', channels: ['In-store', 'Online'], modifiers: 0, type: 'Retail' },
    { id: 'P-4002', sku: 'APP-TEE-CRM', name: 'Heritage Tee — Cream', category: 'Apparel', price: 38.00, cost: 12.40, stock: 86, status: 'active', channels: ['In-store', 'Online'], modifiers: 0, type: 'Retail' },
    { id: 'P-4003', sku: 'APP-CAP-001', name: 'Embroidered Cap', category: 'Accessories', price: 28.00, cost: 7.20, stock: 12, status: 'low', channels: ['In-store', 'Online'], modifiers: 0, type: 'Retail' },
    { id: 'P-4004', sku: 'APP-MUG-001', name: 'Ceramic Mug 12oz', category: 'Accessories', price: 18.00, cost: 4.10, stock: 0, status: 'oos', channels: ['In-store', 'Online'], modifiers: 0, type: 'Retail' },
    { id: 'P-5010', sku: 'BEV-COK-001', name: 'Coke (can)', category: 'Beverages', price: 2.75, cost: 0.55, stock: 240, status: 'active', channels: ['Dine-in', 'Delivery', 'QR'], modifiers: 0, type: 'Restaurant' },
    { id: 'P-5011', sku: 'BEV-SPR-002', name: 'Sparkling Water', category: 'Beverages', price: 3.50, cost: 0.40, stock: 180, status: 'active', channels: ['Dine-in', 'QR'], modifiers: 1, type: 'Restaurant' },
  ],
  modifierGroups: [
    { id: 'MG-001', name: 'Cooking Preference', min: 1, max: 1, required: true, items: ['Rare', 'Medium-rare', 'Medium', 'Medium-well', 'Well done'], linked: 6 },
    { id: 'MG-002', name: 'Cheese Add-ons', min: 0, max: 3, required: false, items: ['American +$1', 'Cheddar +$1.50', 'Swiss +$1.50', 'Pepper Jack +$2'], linked: 4 },
    { id: 'MG-003', name: 'Milk Choice', min: 1, max: 1, required: true, items: ['Whole', '2%', 'Oat +$0.75', 'Almond +$0.75', 'Soy +$0.75'], linked: 8 },
    { id: 'MG-004', name: 'Espresso Shots', min: 0, max: 4, required: false, items: ['Single', 'Double +$1', 'Decaf', 'Half-caf'], linked: 5 },
    { id: 'MG-005', name: 'Pizza Toppings', min: 0, max: 8, required: false, items: ['Mushroom +$2', 'Olive +$1.50', 'Sausage +$3', 'Anchovy +$2', 'Basil +$1'], linked: 3 },
    { id: 'MG-006', name: 'Spice Level', min: 1, max: 1, required: true, items: ['Mild', 'Medium', 'Hot', 'Extra Hot'], linked: 7 },
  ],
  staff: [
    { id: 'S-001', name: 'Maya Chen', email: 'maya@northwind.co', role: 'Admin', loc: 'Flagship — SoHo', status: 'active', clockedIn: true, lastSale: 12 },
    { id: 'S-002', name: 'Diego Ramirez', email: 'diego@northwind.co', role: 'Manager', loc: 'Brooklyn Heights', status: 'active', clockedIn: true, lastSale: 4 },
    { id: 'S-003', name: 'Priya Patel', email: 'priya@northwind.co', role: 'Cashier', loc: 'Flagship — SoHo', status: 'active', clockedIn: true, lastSale: 1 },
    { id: 'S-004', name: 'Marcus Johnson', email: 'marcus@northwind.co', role: 'Kitchen', loc: 'Boston Seaport', status: 'active', clockedIn: true, lastSale: 0 },
    { id: 'S-005', name: 'Sara Lindqvist', email: 'sara@northwind.co', role: 'Waiter', loc: 'Flagship — SoHo', status: 'active', clockedIn: true, lastSale: 6 },
    { id: 'S-006', name: 'Ahmed Hassan', email: 'ahmed@northwind.co', role: 'Manager', loc: 'Chicago — West Loop', status: 'active', clockedIn: false, lastSale: 180 },
    { id: 'S-007', name: 'Yuki Tanaka', email: 'yuki@northwind.co', role: 'Cashier', loc: 'LA — Abbot Kinney', status: 'invited', clockedIn: false, lastSale: null },
    { id: 'S-008', name: 'Owen Park', email: 'owen@northwind.co', role: 'Cashier', loc: 'Austin Domain', status: 'active', clockedIn: true, lastSale: 8 },
    { id: 'S-009', name: 'Isabel Costa', email: 'isabel@northwind.co', role: 'Waiter', loc: 'Miami Wynwood', status: 'active', clockedIn: true, lastSale: 22 },
    { id: 'S-010', name: 'Theo Becker', email: 'theo@northwind.co', role: 'Support', loc: 'HQ', status: 'active', clockedIn: false, lastSale: null },
  ],
  terminals: [
    { id: 'T-1001', locationId: 'L-001', name: 'Front Counter A', loc: 'Flagship — SoHo', device: 'iPad Pro 12.9"', ip: '10.0.4.21', status: 'online', battery: 92, printer: 'EPSON-TM82-A' },
    { id: 'T-1002', locationId: 'L-001', name: 'Front Counter B', loc: 'Flagship — SoHo', device: 'iPad Pro 12.9"', ip: '10.0.4.22', status: 'online', battery: 78, printer: 'EPSON-TM82-A' },
    { id: 'T-1003', locationId: 'L-001', name: 'Bar Station', loc: 'Flagship — SoHo', device: 'iPad Air', ip: '10.0.4.23', status: 'syncing', battery: 64, printer: 'STAR-TSP143' },
    { id: 'T-1004', locationId: 'L-005', name: 'Drive-thru', loc: 'Chicago — West Loop', device: 'Toast Go 2', ip: '10.2.1.14', status: 'online', battery: 88, printer: 'EPSON-TM82-CHI' },
    { id: 'T-1005', locationId: null, name: 'Patio Tablet', loc: 'Miami Wynwood', device: 'iPad Mini', ip: '10.5.1.07', status: 'offline', battery: 12, printer: '—' },
    { id: 'T-1006', locationId: 'L-002', name: 'Counter 1', loc: 'Brooklyn Heights', device: 'Square Register', ip: '10.0.5.10', status: 'online', battery: null, printer: 'STAR-TSP100' },
    { id: 'T-1007', locationId: 'L-004', name: 'Mobile POS 1', loc: 'Boston Seaport', device: 'Toast Go 2', ip: '10.1.2.18', status: 'online', battery: 71, printer: 'BIXOLON-SPP' },
    { id: 'T-1008', locationId: 'L-006', name: 'Retail Counter', loc: 'Lincoln Park Retail', device: 'iPad Pro', ip: '10.2.3.09', status: 'online', battery: 95, printer: 'EPSON-TM30' },
  ],
  liveOrders: [
    { id: '#10394', table: 'T-12', items: 4, total: 64.50, channel: 'Dine-in', status: 'preparing', placed: '2m', staff: 'Sara' },
    { id: '#10395', table: '—', items: 2, total: 12.50, channel: 'QR Order', status: 'new', placed: '38s', staff: '—' },
    { id: '#10396', table: 'T-04', items: 7, total: 128.20, channel: 'Dine-in', status: 'served', placed: '14m', staff: 'Sara' },
    { id: '#10397', table: '—', items: 3, total: 41.75, channel: 'Delivery', status: 'preparing', placed: '5m', staff: 'Diego' },
    { id: '#10398', table: 'T-08', items: 5, total: 87.30, channel: 'Dine-in', status: 'preparing', placed: '8m', staff: 'Isabel' },
    { id: '#10399', table: '—', items: 1, total: 5.75, channel: 'Takeaway', status: 'ready', placed: '11m', staff: 'Priya' },
    { id: '#10400', table: 'T-15', items: 3, total: 54.00, channel: 'Dine-in', status: 'new', placed: '12s', staff: '—' },
    { id: '#10401', table: '—', items: 2, total: 28.50, channel: 'Drive-thru', status: 'ready', placed: '3m', staff: 'Owen' },
  ],
  hourly: [
    { h: '9a', v: 8 }, { h: '10a', v: 14 }, { h: '11a', v: 22 }, { h: '12p', v: 38 },
    { h: '1p', v: 42 }, { h: '2p', v: 31 }, { h: '3p', v: 18 }, { h: '4p', v: 21 },
    { h: '5p', v: 28 }, { h: '6p', v: 44 }, { h: '7p', v: 52 }, { h: '8p', v: 47 },
    { h: '9p', v: 33 }, { h: '10p', v: 19 },
  ],
  topProducts: [
    { name: 'Oat Milk Latte', sales: 482, rev: 2772, share: 100 },
    { name: 'Northwind Classic Burger', sales: 314, rev: 4553, share: 65 },
    { name: 'Margherita Pizza', sales: 198, rev: 3564, share: 41 },
    { name: 'Cortado', sales: 187, rev: 794, share: 39 },
    { name: 'Heritage Tee — Black', sales: 142, rev: 5396, share: 29 },
    { name: 'Double Stack Cheeseburger', sales: 124, rev: 2170, share: 26 },
  ],
};
